[project]
name = "scripts"
version = "0.1.0"
description = "A collection of scripts to create Lingetic language learning courses"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.9.9",
]

[tool.ruff]
line-length = 80
