services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: lingetic
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER environment variable is not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD environment variable is not set}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: